# Generated by Django 4.2.1 on 2023-06-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('product_description', models.TextField()),
                ('image', models.ImageField(default='No image available', upload_to='photos/products')),
                ('quantity', models.IntegerField(null=True)),
                ('product_price', models.IntegerField(null=True)),
            ],
        ),
    ]
