# Generated by Django 4.2.1 on 2023-06-13 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0002_category_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default='no', on_delete=django.db.models.deletion.CASCADE, to='admindashboard.category'),
        ),
    ]
