# Generated by Django 4.2.1 on 2023-06-26 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0005_offer_product_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_variant', models.IntegerField(null=True)),
                ('pice_variant', models.IntegerField(null=True)),
                ('image_variant', models.ImageField(default='No image available', upload_to='photos/product')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admindashboard.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admindashboard.size')),
            ],
        ),
    ]
