# Generated by Django 4.2.1 on 2023-06-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0006_size_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='size',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
