# Generated by Django 4.2.1 on 2023-06-27 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0008_rename_pice_variant_variation_price_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
