# Generated by Django 4.2.1 on 2023-06-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0009_remove_product_image_remove_product_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='price_variant',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='variation',
            name='quantity_variant',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
