# Generated by Django 4.2.1 on 2023-06-21 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_delete_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_no',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
