# Generated by Django 4.2.1 on 2023-07-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderreturn',
            old_name='reason',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='orderreturn',
            name='options',
        ),
        migrations.AddField(
            model_name='orderreturn',
            name='image',
            field=models.ImageField(default=1, upload_to='photos/'),
            preserve_default=False,
        ),
    ]
